export default [
  [
    { code: 'Backquote', shiftChange: ['`', '~', '<', '>', ''] },
    { code: 'Digit1', shiftChange: ['1', '!', '1', '!', ''] },
    { code: 'Digit2', shiftChange: ['2', '@', '2', '"', ''] },
    { code: 'Digit3', shiftChange: ['3', '#', '3', '№', ''] },
    { code: 'Digit4', shiftChange: ['4', '$', '4', ';', ''] },
    { code: 'Digit5', shiftChange: ['5', '%', '5', '%', ''] },
    { code: 'Digit6', shiftChange: ['6', '^', '6', ':', ''] },
    { code: 'Digit7', shiftChange: ['7', '&', '7', '?', ''] },
    { code: 'Digit8', shiftChange: ['8', '*', '8', '*', ''] },
    { code: 'Digit9', shiftChange: ['9', '(', '9', '(', ''] },
    { code: 'Digit0', shiftChange: ['0', ')', '0', ')', ''] },
    { code: 'Minus', shiftChange: ['-', '_', '-', '_', ''] },
    { code: 'Equal', shiftChange: ['=', '+', '=', '+', ''] },
    { code: 'Delete', shiftChange: ['', '', '', '', 'delete'] },
  ],
  [
    { code: 'Tab', shiftChange: ['\t', '\t', '\t', '\t', 'tab'] },
    { code: 'KeyQ', shiftChange: ['q', 'Q', 'й', 'Й', ''] },
    { code: 'KeyW', shiftChange: ['w', 'W', 'ц', 'Ц', ''] },
    { code: 'KeyE', shiftChange: ['e', 'E', 'у', 'У', ''] },
    { code: 'KeyR', shiftChange: ['r', 'R', 'к', 'К', ''] },
    { code: 'KeyT', shiftChange: ['t', 'T', 'е', 'Е', ''] },
    { code: 'KeyY', shiftChange: ['y', 'Y', 'н', 'Н', ''] },
    { code: 'KeyU', shiftChange: ['u', 'U', 'г', 'Г', ''] },
    { code: 'KeyI', shiftChange: ['i', 'I', 'ш', 'Ш', ''] },
    { code: 'KeyO', shiftChange: ['o', 'O', 'щ', 'Щ', ''] },
    { code: 'KeyP', shiftChange: ['p', 'P', 'з', 'З', ''] },
    { code: 'BracketLeft', shiftChange: ['[', '{', 'х', 'Х', ''] },
    { code: 'BracketRight', shiftChange: [']', '}', 'ъ', 'Ъ', ''] },
    { code: 'Backslash', shiftChange: ['\\', '|', 'ё', 'Ё', ''] },
  ],
  [
    { code: 'CapsLock', shiftChange: ['', '', '', '', 'caps'] },
    { code: 'KeyA', shiftChange: ['a', 'A', 'ф', 'Ф', ''] },
    { code: 'KeyS', shiftChange: ['s', 'S', 'ы', 'Ы', ''] },
    { code: 'KeyD', shiftChange: ['d', 'D', 'в', 'В', ''] },
    { code: 'KeyF', shiftChange: ['f', 'F', 'а', 'А', ''] },
    { code: 'KeyG', shiftChange: ['g', 'G', 'п', 'П', ''] },
    { code: 'KeyH', shiftChange: ['h', 'H', 'р', 'Р', ''] },
    { code: 'KeyJ', shiftChange: ['j', 'J', 'о', 'О', ''] },
    { code: 'KeyK', shiftChange: ['k', 'K', 'л', 'Л', ''] },
    { code: 'KeyL', shiftChange: ['l', 'L', 'д', 'Д', ''] },
    { code: 'Semicolon', shiftChange: [';', ':', 'ж', 'Ж', ''] },
    { code: 'Quote', shiftChange: ['\'', '"', 'э', 'Э', ''] },
    { code: 'Enter', shiftChange: ['\n', '\n', '\n', '\n', 'enter'] },
  ],
  [
    { code: 'ShiftLeft', shiftChange: ['', '', '', '', 'shift'] },
    { code: 'KeyZ', shiftChange: ['z', 'Z', 'я', 'Я', ''] },
    { code: 'KeyX', shiftChange: ['x', 'X', 'ч', 'Ч', ''] },
    { code: 'KeyC', shiftChange: ['c', 'C', 'с', 'С', ''] },
    { code: 'KeyV', shiftChange: ['v', 'V', 'м', 'М', ''] },
    { code: 'KeyB', shiftChange: ['b', 'B', 'и', 'И', ''] },
    { code: 'KeyN', shiftChange: ['n', 'N', 'т', 'Т', ''] },
    { code: 'KeyM', shiftChange: ['m', 'M', 'ь', 'Ь', ''] },
    { code: 'Comma', shiftChange: [',', '<', 'б', 'Б', ''] },
    { code: 'Period', shiftChange: ['.', '>', 'ю', 'Ю', ''] },
    { code: 'Slash', shiftChange: ['/', '?', '/', '?', ''] },
    { code: 'ArrowUp', shiftChange: ['&#9652', '&#9652', '&#9652', '&#9652', '&#9652'] },
    { code: 'ShiftRight', shiftChange: ['', '', '', '', 'shift'] },
  ],
  [
    { code: 'FN', shiftChange: ['', '', '', '', 'fn'] },
    { code: 'ControlLeft', shiftChange: ['', '', '', '', 'control'] },
    { code: 'AltLeft', shiftChange: ['', '', '', '', 'option'] },
    { code: 'MetaLeft', shiftChange: ['', '', '', '', 'command'] },
    { code: 'Space', shiftChange: [' ', ' ', ' ', ' ', ' '] },
    { code: 'MetaRight', shiftChange: ['', '', '', '', 'command'] },
    { code: 'AltRight', shiftChange: ['', '', '', '', 'option'] },
    { code: 'ArrowLeft', shiftChange: ['&#9666', '&#9666', '&#9666', '&#9666', '&#9666'] },
    { code: 'ArrowDown', shiftChange: ['&#9662', '&#9662', '&#9662', '&#9662', '&#9662'] },
    { code: 'ArrowRight', shiftChange: ['&#9656', '&#9656', '&#9656', '&#9656', '&#9656'] },
  ],
];
